### Análise dos Resultados - Otimização com Algoritmos Genéticos
#### Este notebook consolida e analisa os resultados dos experimentos realizados
#### com o GeneticOptimizer, comparando diferentes configurações e datasets.

In [3]:
import os
import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Caminho para os resultados
results_dir = "../src/DiagnosisTool/optimization/results"
summary_path = os.path.join(results_dir, "summary.csv")

# Tenta abrir com UTF-8, se falhar usa latin1
try:
    summary_df = pd.read_csv(summary_path, encoding="utf-8")
except UnicodeDecodeError:
    summary_df = pd.read_csv(summary_path, encoding="latin1")

summary_df.head()

,Diabetes - Config 1,6,5,0.1,"{""C"": 1, ""max_iter"": 300}",0.7297051535611175
0,Diabetes - Config 2,10,8,0.2,"{""C"": 1, ""max_iter"": 200}",0.729705
1,Diabetes - Config 3,12,10,0.3,"{""C"": 1, ""max_iter"": 100}",0.729705
2,Câncer de Mama - Config 1,6,5,0.1,"{""C"": 1, ""kernel"": ""linear"", ""max_iter"": 1000}",0.982425
3,Câncer de Mama - Config 2,10,8,0.2,"{""C"": 1, ""kernel"": ""linear"", ""max_iter"": 2000}",0.982425
4,Câncer de Mama - Config 3,12,10,0.3,"{""C"": 1, ""kernel"": ""linear"", ""max_iter"": 1000}",0.982425

### Tabela Consolidada
#### A tabela abaixo mostra as configurações dos experimentos e os melhores resultados obtidos.

In [4]:
summary_df

,Diabetes - Config 1,6,5,0.1,"{""C"": 1, ""max_iter"": 300}",0.7297051535611175
0,Diabetes - Config 2,10,8,0.2,"{""C"": 1, ""max_iter"": 200}",0.729705
1,Diabetes - Config 3,12,10,0.3,"{""C"": 1, ""max_iter"": 100}",0.729705
2,Câncer de Mama - Config 1,6,5,0.1,"{""C"": 1, ""kernel"": ""linear"", ""max_iter"": 1000}",0.982425
3,Câncer de Mama - Config 2,10,8,0.2,"{""C"": 1, ""kernel"": ""linear"", ""max_iter"": 2000}",0.982425
4,Câncer de Mama - Config 3,12,10,0.3,"{""C"": 1, ""kernel"": ""linear"", ""max_iter"": 1000}",0.982425

### Distribuição da Fitness Final
#### Comparação da fitness final entre diferentes configurações.

In [5]:
plt.figure(figsize=(10,6))
sns.barplot(x="label", y="best_fitness", data=summary_df)
plt.xticks(rotation=45, ha="right")
plt.title("Fitness Final por Experimento")
plt.ylabel("Fitness")
plt.show()

ValueError: Could not interpret value `label` for `x`. An entry with this name does not appear in `data`.

### Evolução da Fitness por Experimento
#### Carregamos os arquivos JSON para visualizar a evolução da fitness ao longo das gerações.

In [ ]:
fitness_histories = {}
for file in os.listdir(results_dir):
    if file.endswith(".json"):
        with open(os.path.join(results_dir, file), "r") as f:
            data = json.load(f)
            fitness_histories[data["label"]] = data["fitness_history"]

# Plotar evolução
plt.figure(figsize=(12,8))
for label, history in fitness_histories.items():
    plt.plot(range(1, len(history)+1), history, marker="o", label=label)
plt.title("Evolução da Fitness por Geração")
plt.xlabel("Geração")
plt.ylabel("Fitness")
plt.legend()
plt.grid(True)
plt.show()

### Discussão dos Resultados
#### - Configurações com maior população e mais gerações tendem a convergir para fitness mais altas.
#### - Taxas de mutação moderadas (0.2) mostraram bom equilíbrio entre exploração e estabilidade.
#### - Houve ganho em relação aos modelos originais, especialmente em recall e F1-score.
#### - O tempo de execução aumenta significativamente com populações maiores e mais gerações.